id: 2222c34dc40b515f30dc
bug_link: https://syzkaller.appspot.com/bug?extid=2222c34dc40b515f30dc
title: 'BUG: corrupted list in p9_read_work'
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: 72ea0321088df2c41eca8cc6160c24bcceb56ac7
fix_commit: e4ca13f7d075e551dc158df6af18fb412a1dba0a
datetime: '2018-10-10T09:13:30+09:00'
fix_commit_message: '9p/trans_fd: abort p9_read_work if req status changed


  p9_read_work would try to handle an errored req even if it got put to

  error state by another thread between the lookup (that worked) and the

  time it had been fully read.

  The request itself is safe to use because we hold a ref to it from the

  lookup (for m->rreq, so it was safe to read into the request data buffer

  until this point), but the req_list has been deleted at the same time

  status changed, and client_cb already has been called as well, so we

  should not do either.


  Link: http://lkml.kernel.org/r/1539057956-23741-1-git-send-email-asmadeus@codewreck.org

  Signed-off-by: Dominique Martinet <dominique.martinet@cea.fr>

  Reported-by: syzbot+2222c34dc40b515f30dc@syzkaller.appspotmail.com

  Cc: Eric Van Hensbergen <ericvh@gmail.com>

  Cc: Latchesar Ionkov <lucho@ionkov.net>

  '
submodule:
- net/9p
hunk_count: 2
covered_count: 1
