id: 16c3a70e1e9b29346c43
bug_link: https://syzkaller.appspot.com/bug?extid=16c3a70e1e9b29346c43
title: general protection fault in relay_open_buf
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: 37ea7b630ae5cdea4e8ff381d9d23abfef5939e6
fix_commit: 2c1cf00eeacb784781cf1c9896b8af001246d339
datetime: '2019-01-31T14:01:48+01:00'
fix_commit_message: 'relay: check return of create_buf_file() properly


  If create_buf_file() returns an error, don''t try to reference it later

  as a valid dentry pointer.


  This problem was exposed when debugfs started to return errors instead

  of just NULL for some calls when they do not succeed properly.


  Also, the check for WARN_ON(dentry) was just wrong :)


  Reported-by: Kees Cook <keescook@chromium.org>

  Reported-and-tested-by: syzbot+16c3a70e1e9b29346c43@syzkaller.appspotmail.com

  Reported-by: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>

  Cc: Andrew Morton <akpm@linux-foundation.org>

  Cc: David Rientjes <rientjes@google.com>

  Fixes: ff9fb72bc077 ("debugfs: return error values, not NULL")

  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

  '
submodule:
- kernel
hunk_count: 2
covered_count: 2
